name: PR Merge Notify

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  issues: write

jobs:
  notify-qc:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, '(qc)')
    runs-on: ubuntu-latest
    steps:
      - name: Delay for 2 hours
        run: sleep 5

      - name: Notify QC for Acceptance
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.SYNC_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            const qcReviewer = 'www0527'; // 替換為實際的 QC 人員 GitHub 用戶名
            
            // 提取 issue 編號
            const issueMatch = context.payload.pull_request.title.match(/\(qc\)issue\/(\d+)/i);
            if (issueMatch) {
              const issueNumber = issueMatch[1];
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueNumber,
                body: `@${qcReviewer} PR 已合併到 main 分支，請進行驗收。`
              });
            } else {
              console.error('未找到 issue 編號');
            }
